[package]
name = "rjprof"
version = "0.1.0"
edition = "2021"

[lib]
name = "rjprof"
crate-type = ["cdylib"]
rustflags = ["-A non_snake_case"]

[dependencies]
inferno = "0.12.3"
jni = "0.21.1"
libc = "0.2"
once_cell = "1"

[build-dependencies]
bindgen = "0.69.4"
